services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: 1805866272:AAEVjVuESub14bCqG_BgkgLjWD1lscLdn6A
